read tintColor of the layers
Yanrishatum/haxe-format-tiled pull request #11
Opened 2020-07-05 06:46 UTC by juakob

2020-07-05 08:59 UTC, Yanrishatum requested changes
Apart from inconsistent tint alpha and few formatting nits, I see no issues.

2020-07-05 08:59 UTC, Yanrishatum commented on format/tmx/Reader.hx
> +    return Std.parseInt("0x"+color.substr(1));
I would suggest checking if it's in `ARGB` or `RGB` format, and add `0xff000000` alpha for later to ensure consistency of tint alpha being present in any case.
```suggestion
    if (color.length == 7) return 0xff000000 | Std.parseInt("0x" + color.substr(1));
    return Std.parseInt("0x" + color.substr(1));
```

2020-07-05 08:59 UTC, Yanrishatum commented on format/tmx/Reader.hx
> +  private function parseColor(color:String):Null<Int> {
```suggestion
  private function parseColor(color:String):Null<Int>
  {
```
Format nit.

2020-07-05 08:59 UTC, Yanrishatum commented on format/tmx/Data.hx
> +  /** tint color of the layer */
```suggestion
  /** A color that is multiplied with any graphics drawn by this layer. (since 1.4) */
```
I mostly use description provided by official format specification.

2020-07-06 04:42 UTC, juakob commented
thanks for taking the time!

2020-07-06 07:03 UTC, merged